version: "2.1"

services:
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_STATIC_QUEUES: testqueue;emptyqueue;producequeue
