name: BuildAndTestonEveryPushLinux.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    # Current ubuntu-latest (22+) does not support .NET Framework 4.7.1, thus 20.4.
    name: Build on ubuntu-20.04
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    
    - name: set up docker
      run: docker-compose -f ./Frends.Community.ActiveMQ.Tests/docker-compose.yml up -d

    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Get package name
      id: package_name
      run: |
        $pkg = Get-ChildItem -Path . -Filter *.nupkg -Exclude *.symbols.nupkg -Recurse | Select-Object -First 1
        echo "full_name=$($pkg.FullName)" >> $env:GITHUB_OUTPUT
      
    - name: Push to Frends Community Test Feed
      shell: bash
      run: |       
        curl -X POST "${{ secrets.COMMUNITY_TASKS_API }}?feed_type=test" \
          -H "x-api-key: ${{ secrets.FRENDS_COMMUNITY_TASKS_API_KEY }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"${{ steps.package_name.outputs.full_name }}"
